### ISSUE TITLE
custom storage

### ISSUE THREAD

**Issue by blondie63** [Laravel-Backpack/basset#80]
In my app i just have a /public/storage folder which conflicts with creating the symlink, is there any way to set basset to use another name?

Thanks

**Comment by promatik** [comment]
Hi @blondie63, you can avoid using the symlink at all, it's not mandatory 👌
It's ok to use `/public/storage` directly.

In order to do it, make sure about;
1) If you used the instal command (most probably) basset automatically added the symlink command to your composer.json, you must remove it from there.
2) If you do not plan to use the storage link at all, you can also remove it from the `config\filesystem.php` » `links`. This will avoid any other possible conflict 👌

That's it, just make sure your disk is properly configured, either properly configure the public disk, or create a new one with the perfect settings for basset, and make it the default for basset 👌

Probably the easiest solution is to create a specific disk for basset;

`filesystem.php`
```php
'basset' => [
    'driver' => 'local',
    'root' => public_path(''),
    'url' => '/',
    'visibility' => 'public',
    'throw' => false,
],
```

`.env`
```
BASSET_DISK=basset
```
